### ISSUE TITLE
Is this only for Github Actions

### ISSUE THREAD

**Issue by nathang21** [namaggarwal/clasp-token-action#1]
Would love to integrate into my Gitlab CI workflow, but looks like it might be setup specifically for GH actions. Hard to tell from README.

**Comment by namaggarwal** [comment]
This is specifically for Github. Logic is pretty simple, it just creates a .clasprc file. Gitlab CI doesn't provide plugins as far as I know. If you can point me out to such a feature, I will be happy to extend this for Gitlab.
